import fs from "node:fs";
import path from "node:path";
import { buildPublicData } from "./public-data.mjs";
import { isFlatPublicLayout, projectDir, resolveDataDir } from "./project-layout.mjs";

const flatPublicLayout = isFlatPublicLayout(projectDir);
const workspaceRoot = flatPublicLayout ? projectDir : path.resolve(projectDir, "../..");
const sourceDir = resolveDataDir(projectDir);
const generatedDir = path.join(projectDir, "src", "generated");
const publicDataDir = path.join(projectDir, "public", "data");

const requiredFiles = [
  "skills.json",
  "libraries.json",
  "category-units.json",
  "personal-skills.json",
  "changes.json",
  "starred-skills.json",
  "relations.json",
  "skill-details.json",
  "maintenance-status.json",
];

function readJson(fileName) {
  const filePath = path.join(sourceDir, fileName);
  if (!fs.existsSync(filePath)) {
    throw new Error(`Missing source data: ${filePath}`);
  }
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

for (const dir of [generatedDir, publicDataDir]) {
  fs.mkdirSync(dir, { recursive: true });
}

const skills = readJson("skills.json");
const libraries = readJson("libraries.json");
const categoryUnits = readJson("category-units.json");
const personalSkills = readJson("personal-skills.json");
const changes = readJson("changes.json");
const starredSkills = readJson("starred-skills.json");
const relations = readJson("relations.json");
const skillDetails = readJson("skill-details.json");
const maintenanceStatus = readJson("maintenance-status.json");

const publicData = buildPublicData({
  skills,
  libraries,
  categoryUnits,
  personalSkills,
  changes,
  starredSkills,
  relations,
  skillDetails,
  maintenanceStatus,
});

const latestSnapshotDate = changes
  .map((change) => change?.date)
  .filter((date) => typeof date === "string" && /^\d{4}-\d{2}-\d{2}$/.test(date))
  .sort()
  .at(-1) ?? "1970-01-01";
const generatedSnapshotDate = [latestSnapshotDate, maintenanceStatus.snapshotDate]
  .filter((date) => typeof date === "string" && /^\d{4}-\d{2}-\d{2}$/.test(date))
  .sort()
  .at(-1) ?? "1970-01-01";

const appData = {
  // Tie the bundled snapshot to source data, not the wall clock, so identical
  // inputs produce byte-identical JavaScript and stable Vite asset hashes.
  generatedAt: `${generatedSnapshotDate}T12:00:00.000Z`,
  sourceDir: flatPublicLayout ? "data" : "outputs/data",
  ...publicData,
};

const generatedFile = path.join(generatedDir, "data.generated.ts");
const payload = JSON.stringify(appData, null, 2);
fs.writeFileSync(
  generatedFile,
  [
    "/* This file is generated by scripts/sync-data.mjs. Do not edit by hand. */",
    "import type { AppData } from '../types';",
    "",
    `export const appData = ${payload} as AppData;`,
    "",
  ].join("\n"),
  "utf8",
);

const publicFiles = {
  "skills.json": publicData.skills,
  "libraries.json": publicData.libraries,
  "category-units.json": publicData.categoryUnits,
  "personal-skills.json": publicData.personalSkills,
  "changes.json": publicData.changes,
  "starred-skills.json": publicData.starredSkills,
  "relations.json": publicData.relations,
  "skill-details.json": publicData.skillDetails,
  "maintenance-status.json": publicData.maintenanceStatus,
};

for (const [fileName, value] of Object.entries(publicFiles)) {
  const sourcePath = path.join(sourceDir, fileName);
  const targetPath = path.join(publicDataDir, fileName);
  const sourceValue = readJson(fileName);
  if (JSON.stringify(sourceValue) === JSON.stringify(value)) {
    fs.copyFileSync(sourcePath, targetPath);
  } else {
    fs.writeFileSync(targetPath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
  }
}

console.log(
  `Synced ${publicData.skills.length}/${skills.length} public skills, ${publicData.libraries.length} libraries, ${publicData.categoryUnits.length} categories to ${path.relative(workspaceRoot, generatedFile)}.`,
);
